### ISSUE TITLE
Validation is only on pull_requests needed

### ISSUE THREAD

**Issue by hdjm01** [hdjm01/FPV-Bibliography#73]
The trigger in in **./.github/workflows/test.xml** should be changed.

```
  pull_request:
    branches: [ main ]
  
  push:
    branches: 
      - '*'
    path: 
      - 'src/bibliography.xml'
```

should be changed to this

```
  pull_request:
    branches:
      - '*'
    path: 
      - 'src/bibliography.xml'
```
